# Generated by Django 4.2.7 on 2023-11-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('product_desc', models.CharField(max_length=100)),
                ('product_cost', models.FloatField(help_text='(in $)')),
            ],
        ),
    ]
